stages:
  - test
  - build
  - deploy

variables:
  POSTGRES_DB: homestead
  POSTGRES_USER: root
  POSTGRES_PASSWORD: secret

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - vendor
    - node_modules
    - .yarn

before_script:
  - npm install
  - npm rebuild
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test :
  stage: test
  services:
    - postgres:latest
  image: chilio/laravel-dusk-ci:stable
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate:refresh --seed
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  artifacts:
    paths:
      - ./storage/logs
    expire_in: 1 days
    when: always

test laravel mix:
  image: node:12
  stage: test
  script:
  - npm test

build vues:
  image: node:12
  stage: build
  script:
  - npm run production

deploy staging:
  image: chilio/laravel-dusk-ci:stable
  stage: deploy
  script:
  - ./deployer.phar deploy dev
  only:
    refs:
      - dev

deploy prod:
  image: chilio/laravel-dusk-ci:stable
  stage: deploy
  script:
  - ./deployer.phar deploy prod
  when: manual
  only:
    refs:
      - master