stages:
  - test
  - deploy

variables:
  POSTGRES_DB: homestead
  POSTGRES_USER: root
  POSTGRES_PASSWORD: secret

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - vendor
    - node_modules
    - public
    - .yarn

test:
  stage: test
  services:
    - postgres:latest
  image: chilio/laravel-dusk-ci:stable
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate:refresh --seed
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  artifacts:
    paths:
      - ./storage/logs
    expire_in: 1 days
    when: always

deploy_staging:
  image: chilio/laravel-dusk-ci:stable
  stage: deploy
  script:
  - chmod 400 ssh_key/id_rsa
  - chmod 400 ssh_key/id_rsa.pub
  - if [ $CI_COMMIT_REF_NAME = "master" ]; then ./deployer.phar deploy prod; else ./deployer.phar deploy dev; fi
  # - ./deployer.phar deploy dev